/**
 * Волна Деньги / Компания / Персонал / Настройки / Главное —
 * тонкие журналы для закрытия оставшихся «нет» карты УНФ.
 * Подключается в parity-batch-a (append), не трогает Batch A UI.
 */

type WaveMeta = {
  key: string;
  title: string;
  prefix: string;
  note: string;
  section: 'purchases' | 'sales' | 'warehouse' | 'money' | 'staff' | 'company' | 'settings' | 'home';
  map_ids: string[];
};

export const MONEY_WAVE_THIN_JOURNALS: WaveMeta[] = [
  // ——— Главное ———
  {
    key: 'home_month_close',
    title: 'Закрытие месяца',
    prefix: 'ЗМ',
    note: 'Чеклист закрытия месяца. Полный регламент остаётся в 1С; здесь — статус задач Учёта №1.',
    section: 'home',
    map_ids: ['home.month_close'],
  },
  {
    key: 'home_edo',
    title: 'ЭДО (текущие дела)',
    prefix: 'ЭДО',
    note: 'ЭДО / Диадок остаётся у 1С. Журнал напоминаний в Учёте №1 (пусто OK).',
    section: 'home',
    map_ids: ['home.edo'],
  },

  // ——— Деньги ———
  {
    key: 'money_advance_reports',
    title: 'Авансовые отчеты',
    prefix: 'АО',
    note: 'Локальный журнал авансовых отчётов. Пусто OK.',
    section: 'money',
    map_ids: ['money.advance_reports'],
  },
  {
    key: 'money_loan_contracts',
    title: 'Договоры кредитов и займов',
    prefix: 'ДКЗ',
    note: 'Справочник договоров кредитов/займов (локально).',
    section: 'money',
    map_ids: ['money.loan_contracts'],
  },
  {
    key: 'money_loan_accruals',
    title: 'Начисления по кредитам и займам',
    prefix: 'НКЗ',
    note: 'Журнал начислений. Без банковского автопроведения.',
    section: 'money',
    map_ids: ['money.loan_accruals'],
  },
  {
    key: 'money_plan_docs',
    title: 'Документы планирования денег',
    prefix: 'ДПД',
    note: 'Планирование ДДС. Связано с платёжным календарём.',
    section: 'money',
    map_ids: ['money.plan_docs'],
  },
  {
    key: 'money_plan_in',
    title: 'Поступления денег (план)',
    prefix: 'ПДП',
    note: 'Плановые поступления.',
    section: 'money',
    map_ids: ['money.plan_in'],
  },
  {
    key: 'money_plan_transfer',
    title: 'Перемещения денег (план)',
    prefix: 'ПМП',
    note: 'Плановые перемещения между кассами/счетами.',
    section: 'money',
    map_ids: ['money.plan_transfer'],
  },
  {
    key: 'money_spend_requests',
    title: 'Заявки на расход денег',
    prefix: 'ЗРД',
    note: 'Заявки на расход. Одобрение владельца — отдельно (Точка).',
    section: 'money',
    map_ids: ['money.spend_requests'],
  },
  {
    key: 'money_refund_requests',
    title: 'Требования возврата денег',
    prefix: 'ТВД',
    note: 'На основании складского возврата товара клиенту. Сумма = цена последней продажи.',
    section: 'money',
    map_ids: ['money.refund_requests'],
  },
  {
    key: 'money_close_planned',
    title: 'Закрытие планируемых оплат',
    prefix: 'ЗПО',
    note: 'Закрытие плановых оплат по факту.',
    section: 'money',
    map_ids: ['money.close_planned'],
  },
  {
    key: 'money_sf_advance',
    title: 'Регистрация СФ на аванс',
    prefix: 'СФА',
    note: 'Счета-фактуры на аванс (локальный журнал).',
    section: 'money',
    map_ids: ['money.sf_advance'],
  },
  {
    key: 'money_extra',
    title: 'Дополнительные обработки (деньги)',
    prefix: 'ДОД',
    note: 'Реестр доп. обработок раздела Деньги.',
    section: 'money',
    map_ids: ['money.extra'],
  },

  // ——— Персонал ———
  {
    key: 'staff_bonus_policy',
    title: 'Положения о премировании',
    prefix: 'ППР',
    note: 'Положения о премировании (текст/черновики).',
    section: 'staff',
    map_ids: ['staff.bonus_policy'],
  },
  {
    key: 'staff_time_plan',
    title: 'Планирование времени сотрудников',
    prefix: 'ПВС',
    note: 'Планирование времени. Полный СТО-календарь — позже.',
    section: 'staff',
    map_ids: ['staff.time_plan'],
  },
  {
    key: 'staff_daily_reports',
    title: 'Ежедневные отчеты',
    prefix: 'ЕОТ',
    note: 'Ежедневные отчёты сотрудников.',
    section: 'staff',
    map_ids: ['staff.daily_reports'],
  },
  {
    key: 'staff_pdn_consent',
    title: 'Согласия на обработку ПДн',
    prefix: 'ПДН',
    note: 'Журнал согласий на обработку персональных данных.',
    section: 'staff',
    map_ids: ['staff.pdn_consent'],
  },
  {
    key: 'staff_payroll_docs',
    title: 'Документы по зарплате',
    prefix: 'ДЗП',
    note: 'Кадрово-зарплатные документы (локально). ЗП СТО — отдельно.',
    section: 'staff',
    map_ids: ['staff.payroll_docs'],
  },
  {
    key: 'staff_payroll_accrual',
    title: 'Начисления зарплаты',
    prefix: 'НЗП',
    note: 'Начисления ЗП. Без полного расчёта УНФ.',
    section: 'staff',
    map_ids: ['staff.payroll_accrual'],
  },
  {
    key: 'staff_pay_sheets',
    title: 'Платежные ведомости',
    prefix: 'ПВ',
    note: 'Платёжные ведомости (черновики).',
    section: 'staff',
    map_ids: ['staff.pay_sheets'],
  },
  {
    key: 'staff_timesheets',
    title: 'Табели',
    prefix: 'ТБ',
    note: 'Табели учёта рабочего времени.',
    section: 'staff',
    map_ids: ['staff.timesheets'],
  },
  {
    key: 'staff_loans',
    title: 'Договоры кредитов и займов (персонал)',
    prefix: 'ДЗС',
    note: 'Займы сотрудникам (локально).',
    section: 'staff',
    map_ids: ['staff.loans'],
  },
  {
    key: 'staff_accrual_kinds',
    title: 'Виды начислений и удержаний',
    prefix: 'ВНУ',
    note: 'Справочник видов начислений/удержаний.',
    section: 'staff',
    map_ids: ['staff.accrual_kinds'],
  },
  {
    key: 'staff_calc_indicators',
    title: 'Показатели расчетов',
    prefix: 'ПРС',
    note: 'Показатели для расчёта премий/ЗП.',
    section: 'staff',
    map_ids: ['staff.calc_indicators'],
  },
  {
    key: 'staff_bonus_rules',
    title: 'Правила расчета премий',
    prefix: 'ПрП',
    note: 'Правила расчёта премий.',
    section: 'staff',
    map_ids: ['staff.bonus_rules'],
  },
  {
    key: 'staff_bonus_terms',
    title: 'Условия начисления премий',
    prefix: 'УНП',
    note: 'Условия начисления премий.',
    section: 'staff',
    map_ids: ['staff.bonus_terms'],
  },
  {
    key: 'staff_extra',
    title: 'Отчеты / Доп. обработки (персонал)',
    prefix: 'ДОП',
    note: 'Отчёты и доп. обработки раздела Персонал.',
    section: 'staff',
    map_ids: ['staff.extra'],
  },

  // ——— Компания ———
  {
    key: 'company_chart_accounts',
    title: 'План счетов',
    prefix: 'ПС',
    note: 'Управленческий план счетов (заготовка). Бухучёт 1С не заменяется.',
    section: 'company',
    map_ids: ['company.chart_accounts'],
  },
  {
    key: 'company_operations',
    title: 'Операции',
    prefix: 'ОП',
    note: 'Прочие операции компании (локальный журнал).',
    section: 'company',
    map_ids: ['company.operations'],
  },
  {
    key: 'company_other_costs',
    title: 'Прочие затраты',
    prefix: 'ПЗ',
    note: 'Прочие затраты.',
    section: 'company',
    map_ids: ['company.other_costs'],
  },
  {
    key: 'company_tax_accruals',
    title: 'Начисления налогов',
    prefix: 'НН',
    note: 'Начисления налогов (черновики). Закрытие месяца — в 1С.',
    section: 'company',
    map_ids: ['company.tax_accruals'],
  },
  {
    key: 'company_month_close',
    title: 'Закрытие месяца (компания)',
    prefix: 'ЗМК',
    note: 'Чеклист. Полное закрытие месяца остаётся в 1С.',
    section: 'company',
    map_ids: ['company.month_close'],
  },
  {
    key: 'company_etrn',
    title: 'Электронные перевозочные документы',
    prefix: 'ЭПДК',
    note: 'ЭПД. Без live ЭДО.',
    section: 'company',
    map_ids: ['company.etrn'],
  },
  {
    key: 'company_opening_balances',
    title: 'Ввод начальных остатков',
    prefix: 'ВНО',
    note: 'Cutover / начальные остатки. Отдельный контур.',
    section: 'company',
    map_ids: ['company.opening_balances'],
  },
  {
    key: 'company_import_tools',
    title: 'Загрузка из УТ / БП / Розницы / Excel',
    prefix: 'ЗИМ',
    note: 'Миграционные утилиты. Не замена загрузчиков 1С.',
    section: 'company',
    map_ids: ['company.import_tools'],
  },
  {
    key: 'company_assistant',
    title: 'Ассистент УНФ',
    prefix: 'АУ',
    note: 'Ассистент 1С не переносится. Справка по Учёту №1.',
    section: 'company',
    map_ids: ['company.assistant'],
  },
  {
    key: 'company_extra',
    title: 'Дополнительные обработки (компания)',
    prefix: 'ДОК',
    note: 'Реестр доп. обработок раздела Компания.',
    section: 'company',
    map_ids: ['company.extra'],
  },

  // ——— Настройки ———
  {
    key: 'settings_more_features',
    title: 'Еще больше возможностей',
    prefix: 'ЕВВ',
    note: 'Каталог возможностей Учёта №1 ( whitelabel вместо 1С).',
    section: 'settings',
    map_ids: ['settings.more_features'],
  },
  {
    key: 'settings_feature_request',
    title: 'Не нашли нужную возможность?',
    prefix: 'ННВ',
    note: 'Заявки на функции → идеи/ошибки.',
    section: 'settings',
    map_ids: ['settings.feature_request'],
  },
  {
    key: 'settings_mail_sms',
    title: 'Почта и SMS',
    prefix: 'ПСМС',
    note: 'Настройки почты/SMS. Рассылки 1С не переносятся.',
    section: 'settings',
    map_ids: ['settings.mail_sms'],
  },
  {
    key: 'settings_maintenance',
    title: 'Обслуживание',
    prefix: 'ОБС',
    note: 'Обслуживание: бэкапы, restore-drill, health.',
    section: 'settings',
    map_ids: ['settings.maintenance'],
  },
  {
    key: 'settings_internet_support',
    title: 'Интернет-поддержка и сервисы',
    prefix: 'ИПС',
    note: 'Внешние сервисы (Точка, Amo, S3, СДЭК).',
    section: 'settings',
    map_ids: ['settings.internet_support'],
  },
  {
    key: 'settings_data_fix',
    title: 'Корректировка данных',
    prefix: 'КД',
    note: 'Сервисные корректировки. Опасные операции — только admin.',
    section: 'settings',
    map_ids: ['settings.data_fix'],
  },
  {
    key: 'settings_cloud',
    title: 'Работа в облаке',
    prefix: 'ОБЛ',
    note: 'Облачный режим 1С не используется. Учёт №1 на VPS.',
    section: 'settings',
    map_ids: ['settings.cloud'],
  },
  {
    key: 'settings_edo_exchange',
    title: 'Обмен электронными документами',
    prefix: 'ЭДОБ',
    note: 'ЭДО остаётся у 1С / Диадок.',
    section: 'settings',
    map_ids: ['settings.edo_exchange'],
  },
  {
    key: 'settings_ocr',
    title: 'Распознавание документов',
    prefix: 'OCR',
    note: 'Очередь OCR (заготовка).',
    section: 'settings',
    map_ids: ['settings.ocr'],
  },
  {
    key: 'settings_business_network',
    title: '1С:Бизнес-сеть',
    prefix: 'БСС',
    note: '1С:Бизнес-сеть не подключается в Учёте №1.',
    section: 'settings',
    map_ids: ['settings.business_network'],
  },
  {
    key: 'settings_reconcile_1c',
    title: '1С:Сверка 2.0',
    prefix: 'СВР',
    note: 'Сервис 1С:Сверка не в scope v1.',
    section: 'settings',
    map_ids: ['settings.reconcile_1c'],
  },
  {
    key: 'settings_1c_nomenclature',
    title: '1С:Номенклатура',
    prefix: '1СН',
    note: 'Каталог 1С:Номенклатура. Свой каталог — /products.',
    section: 'settings',
    map_ids: ['settings.1c_nomenclature'],
  },
  {
    key: 'settings_rmk',
    title: '1С:РМК / Касса / Мобильная касса',
    prefix: 'РМК',
    note: 'РМК 1С не переносится. АТОЛ prepared; live — skip.',
    section: 'settings',
    map_ids: ['settings.rmk'],
  },
  {
    key: 'settings_mobile_apps',
    title: 'Каталог мобильных приложений',
    prefix: 'МПЛ',
    note: 'Каталог МП 1С. Сборка склада — /pick.',
    section: 'settings',
    map_ids: ['settings.mobile_apps'],
  },
  {
    key: 'settings_telephony',
    title: 'Облачная телефония',
    prefix: 'ТЕЛ',
    note: 'МегаФон → Amo вне WMS.',
    section: 'settings',
    map_ids: ['settings.telephony'],
  },
  {
    key: 'settings_mailings',
    title: 'Почта, рассылки и SMS',
    prefix: 'РСС',
    note: 'Массовые рассылки не в scope v1.',
    section: 'settings',
    map_ids: ['settings.mailings'],
  },
  {
    key: 'settings_chats',
    title: 'Чаты и видеозвонки',
    prefix: 'ЧАТ',
    note: 'Внутренние чаты сотрудников /chats (без видеозвонков).',
    section: 'settings',
    map_ids: ['settings.chats'],
  },
  {
    key: 'settings_vetis',
    title: 'Интеграция с ВетИС (Меркурий)',
    prefix: 'ВЕТ',
    note: 'Не релевантно для ассортимента.',
    section: 'settings',
    map_ids: ['settings.vetis'],
  },
  {
    key: 'settings_gism',
    title: 'Интеграция с ГИСМ',
    prefix: 'ГИСМ',
    note: 'Не в scope.',
    section: 'settings',
    map_ids: ['settings.gism'],
  },
  {
    key: 'settings_egais',
    title: 'Интеграция с ЕГАИС',
    prefix: 'ЕГА',
    note: 'Не релевантно.',
    section: 'settings',
    map_ids: ['settings.egais'],
  },
  {
    key: 'settings_delete_objects',
    title: 'Удаление объектов',
    prefix: 'УДЛ',
    note: 'Сервисное удаление. Только admin; audit обязателен.',
    section: 'settings',
    map_ids: ['settings.delete_objects'],
  },
  {
    key: 'settings_ib_collapse',
    title: 'Свертка ИБ',
    prefix: 'СИБ',
    note: 'Свертка ИБ 1С не применяется к SQLite Учёта №1.',
    section: 'settings',
    map_ids: ['settings.ib_collapse'],
  },
  {
    key: 'settings_extra',
    title: 'Дополнительные обработки (настройки)',
    prefix: 'ДОН',
    note: 'Реестр доп. обработок раздела Настройки.',
    section: 'settings',
    map_ids: ['settings.extra'],
  },
];
